# Train Test Split

# Import Libraries

In [2]:
import numpy as np
from sklearn.model_selection import train_test_split

# Generate Some Data To Split

In [4]:
a = np.arange(1,101)

In [6]:
a

array([  1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,  13,
        14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,  26,
        27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,  39,
        40,  41,  42,  43,  44,  45,  46,  47,  48,  49,  50,  51,  52,
        53,  54,  55,  56,  57,  58,  59,  60,  61,  62,  63,  64,  65,
        66,  67,  68,  69,  70,  71,  72,  73,  74,  75,  76,  77,  78,
        79,  80,  81,  82,  83,  84,  85,  86,  87,  88,  89,  90,  91,
        92,  93,  94,  95,  96,  97,  98,  99, 100])

In [7]:
b = np.arange(501,601)
b

array([501, 502, 503, 504, 505, 506, 507, 508, 509, 510, 511, 512, 513,
       514, 515, 516, 517, 518, 519, 520, 521, 522, 523, 524, 525, 526,
       527, 528, 529, 530, 531, 532, 533, 534, 535, 536, 537, 538, 539,
       540, 541, 542, 543, 544, 545, 546, 547, 548, 549, 550, 551, 552,
       553, 554, 555, 556, 557, 558, 559, 560, 561, 562, 563, 564, 565,
       566, 567, 568, 569, 570, 571, 572, 573, 574, 575, 576, 577, 578,
       579, 580, 581, 582, 583, 584, 585, 586, 587, 588, 589, 590, 591,
       592, 593, 594, 595, 596, 597, 598, 599, 600])

# Split The Data

In [8]:
train_test_split(a)

[array([ 50,  43,  78,  47,  65,  45,  71,  66,  54,  75,  60,  27,  44,
         92,  99,  37,  57,   7,  88,  53,  85,  51,  35,  97, 100,  55,
         29,   1,  96,  91,  17,  30,  86,  90,  58,  83,  63,  56,   4,
          3,  42,  46,  32,  89,  38,  87,  59,  98,  80,  74,  41,  68,
         72,  79,  13,  93,  23,  31,   6,  12,  69,  82,  24,  19,  40,
         77,  67,   5,  94,  39,  52,  18,  95,  14,  28]),
 array([76, 62, 36, 48, 33, 11, 49, 61, 73, 25, 22, 84,  2, 10,  9, 70, 21,
        34, 64,  8, 26, 16, 20, 15, 81])]

In [30]:
a_train, a_test, b_train, b_test = train_test_split(a,b,test_size=0.15,random_state=2)

# Explore The Result

In [31]:
a_train.shape, a_test.shape

((85,), (15,))

In [32]:
a_train

array([22,  4, 30, 62, 80, 36, 12, 85, 45, 74,  6, 26, 78, 75, 63, 66,  2,
       19, 49, 37, 79,  7, 90, 92, 11, 13, 54, 88, 55, 96, 33, 20, 27, 61,
       56, 10, 97, 18, 60, 58, 42, 65, 46, 98,  9, 72, 95, 91, 99, 87, 81,
       51, 53, 67, 89, 71, 47, 69, 70, 82, 59, 34, 39, 52, 43,  5, 68, 40,
       38, 21, 32, 64, 48, 86, 94, 50, 35,  8, 76, 83, 44, 23, 73, 16, 41])

In [33]:
a_test

array([ 84,  31,  57,  25,  17,  24,   3,  28,  29,  14, 100,  93,  77,
        15,   1])

In [34]:
b_train.shape,b_test.shape

((85,), (15,))

In [35]:
b_train

array([522, 504, 530, 562, 580, 536, 512, 585, 545, 574, 506, 526, 578,
       575, 563, 566, 502, 519, 549, 537, 579, 507, 590, 592, 511, 513,
       554, 588, 555, 596, 533, 520, 527, 561, 556, 510, 597, 518, 560,
       558, 542, 565, 546, 598, 509, 572, 595, 591, 599, 587, 581, 551,
       553, 567, 589, 571, 547, 569, 570, 582, 559, 534, 539, 552, 543,
       505, 568, 540, 538, 521, 532, 564, 548, 586, 594, 550, 535, 508,
       576, 583, 544, 523, 573, 516, 541])

In [36]:
b_test

array([584, 531, 557, 525, 517, 524, 503, 528, 529, 514, 600, 593, 577,
       515, 501])